name: padi
description: "P.A.D.I. - Predictive Agriculture and Disease Intelligence"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_tts: ^4.2.5
  camera: ^0.11.2
  image_picker: ^1.2.1
  pdf: ^3.11.3
  printing: ^5.14.2
  url_launcher: ^6.3.2

  cupertino_icons: ^1.0.8

  # HTTP client untuk komunikasi dengan REST API Laravel
  dio: ^5.9.0

  # State management dan dependency injection
  flutter_riverpod: ^3.3.2

  # Penyimpanan token autentikasi secara aman
  flutter_secure_storage: ^10.3.1

  # Routing, redirect autentikasi, dan protected route
  go_router: ^17.5.0

  # GIS, Peta dan Batas Polygon Wilayah
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

  # GPS Geolocation & Permission
  geolocator: ^14.0.3
  permission_handler: ^12.0.1
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Mocking untuk unit test
  mocktail: ^1.0.4

  # Launcher Icons Generator
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/padi-logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0E3E28"
  adaptive_icon_foreground: "assets/images/padi-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/